In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib .pyplot as plt 
%matplotlib inline
from sklearn import linear_model

In [32]:
list =[[2600,3.0,20,550000],[3000,4.0,15,565000],[3200,0,18,610000],[3600,3.0,30,595000],[4000,5.0,8,760000]]


In [33]:
list

[[2600, 3.0, 20, 550000],
 [3000, 4.0, 15, 565000],
 [3200, 0, 18, 610000],
 [3600, 3.0, 30, 595000],
 [4000, 5.0, 8, 760000]]

In [34]:
 df = pd.DataFrame(list,columns=["area","bedrooms","age","price"])

In [35]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       0.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [36]:
median = np.median(df["bedrooms"])

In [37]:
median

3.0

In [38]:
df["bedrooms"].replace(0,df["bedrooms"].median())

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [39]:
median_bedrooms = df["bedrooms"].median()
df["bedrooms"] = df["bedrooms"].replace(0,median_bedrooms)

In [40]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [41]:
reg = linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [42]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [43]:
reg.intercept_

383724.9999999998

In [46]:
reg.predict([[3000,4,40]])

C:\Users\abc\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([418375.])

In [49]:
y = 3000*137.25+4*(-26025)+40*(-6825)+383724.9999999998

In [50]:
y

418374.9999999998

In [51]:
reg.predict([[2500,4,5]])

C:\Users\abc\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [52]:
z= 2500* 137.25+4*(-26025)+5*(-6825)+383724.9999999998

In [53]:
z

588624.9999999998